### ISSUE TITLE
Can't use system installed certs

### ISSUE THREAD

**Issue by aiguofer** [flathub/io.dbeaver.DBeaverCommunity#1]
When I launch the Dbeaver flatpak, it doesn't seem to correctly pick up my system certs. In my host system, java uses /etc/pki/java/cacerts by default.

Looking at https://github.com/p11-glue/p11-kit/issues/68, I tried running:
```
flatpak run --command=p11tool io.dbeaver.DBeaverCommunity --list-all-certs --provider=p11-kit-client.so pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
```
and it correctly shows the certs in my system. 

However, if I run only:
```
flatpak run --command=p11tool io.dbeaver.DBeaverCommunity --list-all-certs
```
I don't see my system certs.

I'm thinking the issue is that the java cacerts works differently from the regularly installed certs (I don't know much about certs in general).

**Comment by aiguofer** [comment]
Potentially related: https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk10/issues/4

I tried running the commands in https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk10/issues/4#issuecomment-428412497 and indeed got a different number of certs inside the flatpak and in my host.

**Comment by TingPing** [comment]
It probably uses OpenSSL which doesn't respect p11.

**Comment by aiguofer** [comment]
Well, if I copy my system `cacerts` file into my home directory and start it using:

```
flatpak run --branch=stable --arch=x86_64 --command=dbeaver io.dbeaver.DBeaverCommunity -vmargs -Djavax.net.ssl.trustStore=$HOME/cacerts
```

it works as expected. It seems like the issue is with the java keystore not using the system certs, but no clue what the "right fix" for this is.

**Comment by aiguofer** [comment]
I tried re-building the flatpak with org.freedesktop.Sdk.Extension.openjdk11 and still no luck. I also tried changing the launcher to make sure it was using the java version installed by the JDK and still no luck.

**Comment by aiguofer** [comment]
Well.... with the latest version (5.3.0) running as I did above doesn't work anymore. It gives me the following error:

```
2018-12-17 19:05:55.640 - Internal error in workbench lifecycle
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
        at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:505)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
        ... 23 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 25 more
```

**Comment by aiguofer** [comment]
Btw, if I install the RPM and run `dbeaver -vmargs -Djavax.net.ssl.trustStore=/home/rdu/difernan/cacerts` it works as expected, so the issue is only for the flatpak.

**Comment by p1u3o** [comment]
Sorry to bump a fairly old issue, but could you not just mount the host ro and read certs from /run/host/etc/pki/ca-trust/extracted/java/cacerts ?
